# eLCS Complete User Guide

Author: Robert Zhang - University of Pennsylvania, B.S.E Computer Science, B.S.E. Economics (SEAS '22, WH '22)

Advisor: Ryan Urbanowicz, PhD - University of Pennsylvania, Department of Biostatics, Epidemiology, and Informatics & Institue for Biomedical Informatics (IBI)

Date: 02/24/2020

Requirements: Anaconda (with Python 3)
<ul>
    <li>Install most recent version of Anaconda</li>
</ul>

## Introduction

This notebook presents a complete user guide to the eLCS scikit-learn package as well as auxilliary helper objects. eLCS is a supervised learning variant of the Learning Classifier System. In general, Learning Classifier Systems (LCSs) are a classification of Rule Based Machine Learning Algorithms that have been shown to perform well on problems involving high amounts of heterogeneity and epistasis. Well designed LCSs are also highly human interpretable. LCS variants have been shown to adeptly handle supervised and reinforced, classification and regression, online and offline learning problems, as well as missing or unbalanced data. These characteristics of versatility and interpretability give LCSs a wide range of potential applications, notably those in biomedicine. This package is still under active development and we encourage you to check back on this repository for updates.

eLCS, or Educational Learning Classifier System, implements the core components of a Michigan-Style Learning Classifier System (where the system's genetic algorithm operates on a rule level, evolving a population of rules with each their own parameters) in an easy to understand way, while still being highly functional in solving ML problems.

While Learning Classifier Systems are commonly applied to genetic analyses, where epistatis (i.e. feature interactions) is common, the eLCS algorithm implemented in this package can be applied to almost any supervised classification data set and supports:

<ul>
    <li>Feature sets that are discrete/categorical, continuous-valued or a mix of both</li>
    <li>Data with missing values</li>
    <li>Binary Classification Problems (Binary Endpoints)</li>
    <li>Multi-class Classification Problems (Multi-class Endpoints)</li>
</ul>

It is important to mention that the eLCS package does not currently support regression problems (continuous endpoints). Regression functionality is built into the package. However, we have decided to disable it for this version, since eLCS performs best on purely classification problems.

## Notebook Organization

**Part 1: Loading Data**
<ul>
    <li> Dataset format requirements for eLCS</li>
    <li> Method 1: Loading data using pandas</li>
    <li> Method 2: Loading data using StringEnumerator</li>
</ul>

**Part 2: Initializing scikit-learn eLCS Classifier Object**
<ul>
    <li> Basic Initialization</li>
    <li> Overview of all eLCS initialization parameters and default values</li>
</ul>

**Part 3: Model Training and Testing**
<ul>
    <li> model.fit(X,y) and how it works</li>
    <li> model.predict(X), model.predict_proba(X)</li>
    <li> model Cross Validation and Scoring</li>
    <li>ROC/AUC/PRC curves </li>
</ul>

**Part 4: Data Collection and Export**
<ul>
    <li> evalWhileFit, trackingFrequency, learningCheckpoints </li>
    <li> Exporting and Accessing Iteration Tracking Data </li>
    <li> Exporting and Accessing Rule Population Data </li>
</ul>
      


## Part 1: Loading Data

### Dataset Format Requirement for eLCS

There are 4 requirements for the dataset:
<ul>
    <li>Data Attributes for all data instances are represented by an <b>nxm</b> numpy.ndarray, where <b>n</b> = # of instances and <b>m</b> = # of attributes for each instance</li>
    <li>Data Phenotypes for all data instances are represented by a 1 dimensional numpy.ndarray of length <b>n</b></li>
    <li>Both the <b>nxm</b> attribute array and the length <b>n</b> phenotype array are fully numeric. This means that every element in each array must be convertable to a float. String, boolean types are not permitted (of course, boolean datasets can be represented by binary 0s and 1s). It is important to mention that missing data in the attribute dataset is acceptable, if represented as a NaN type within the array. Missing data in the phenotype array is not acceptable.</li>
    <li>As mentioned aboved, the problem must be a classification problem. This version does not support regression problems.</li>
</ul>

The package includes automated parameter checking that will raise an Exception at the start of training if the dataset does not meet the above requirements.


### Loading Data Method 1: Using pandas

There are many ways you can derive the attribute and phenotype array. One most common method is by using pandas via reading from a csv file, as the below code demonstrates with the a 6 bit multiplexer dataset:

In [1]:
import pandas as pd

#Read from CSV file
data = pd.read_csv("Datasets/Real/Multiplexer6.csv")

#Specify the dataset's phenotype label
classLabel = "class"

#Derive the attribute and phenotype array using the phenotype label
dataFeatures = data.drop(classLabel,axis = 1).values
dataPhenotypes = data[classLabel].values

#Optional: Retrieve the headers for each attribute as a length n array
dataHeaders = data.drop(classLabel,axis=1).columns.values

print("Data Features")
print(dataFeatures)
print("\nData Phenotypes")
print(dataPhenotypes)
print("\nData Headers")
print(dataHeaders)

Data Features
[[0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 0 0 1 1]
 [0 0 0 1 0 0]
 [0 0 0 1 0 1]
 [0 0 0 1 1 0]
 [0 0 0 1 1 1]
 [0 0 1 0 0 0]
 [0 0 1 0 0 1]
 [0 0 1 0 1 0]
 [0 0 1 0 1 1]
 [0 0 1 1 0 0]
 [0 0 1 1 0 1]
 [0 0 1 1 1 0]
 [0 0 1 1 1 1]
 [0 1 0 0 0 0]
 [0 1 0 0 0 1]
 [0 1 0 0 1 0]
 [0 1 0 0 1 1]
 [0 1 0 1 0 0]
 [0 1 0 1 0 1]
 [0 1 0 1 1 0]
 [0 1 0 1 1 1]
 [0 1 1 0 0 0]
 [0 1 1 0 0 1]
 [0 1 1 0 1 0]
 [0 1 1 0 1 1]
 [0 1 1 1 0 0]
 [0 1 1 1 0 1]
 [0 1 1 1 1 0]
 [0 1 1 1 1 1]
 [1 0 0 0 0 0]
 [1 0 0 0 0 1]
 [1 0 0 0 1 0]
 [1 0 0 0 1 1]
 [1 0 0 1 0 0]
 [1 0 0 1 0 1]
 [1 0 0 1 1 0]
 [1 0 0 1 1 1]
 [1 0 1 0 0 0]
 [1 0 1 0 0 1]
 [1 0 1 0 1 0]
 [1 0 1 0 1 1]
 [1 0 1 1 0 0]
 [1 0 1 1 0 1]
 [1 0 1 1 1 0]
 [1 0 1 1 1 1]
 [1 1 0 0 0 0]
 [1 1 0 0 0 1]
 [1 1 0 0 1 0]
 [1 1 0 0 1 1]
 [1 1 0 1 0 0]
 [1 1 0 1 0 1]
 [1 1 0 1 1 0]
 [1 1 0 1 1 1]
 [1 1 1 0 0 0]
 [1 1 1 0 0 1]
 [1 1 1 0 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]
 [1 1 1 1 0 1]
 [1 1 1 1 1 0]
 [1 1 1 1 1 1]]

Data Phenotypes
[0 0 0 0

Below is another code snippet that uses the same method, but with a dataset that contains missing values. Note that all missing values must be represented as a NaN type when used in the eLCS scikit model.

In [2]:
import pandas as pd

#Read from CSV file
data = pd.read_csv("Datasets/Tests/MissingFeatureData.csv")

#Specify the dataset's phenotype label
classLabel = "phenotype"

#Derive the attribute and phenotype array using the phenotype label
dataFeatures = data.drop(classLabel,axis = 1).values
dataPhenotypes = data[classLabel].values

#Optional: Retrieve the headers for each attribute as a length n array
dataHeaders = data.drop(classLabel,axis=1).columns.values

print("Data Features")
print(dataFeatures)
print("\nData Phenotypes")
print(dataPhenotypes)
print("\nData Headers")
print(dataHeaders)

Data Features
[[ 1. nan  1.  4.]
 [ 2.  0.  1. nan]
 [ 4. nan  1.  2.]
 [nan  1. nan  1.]
 [ 6. nan  1.  1.]]

Data Phenotypes
[1 0 1 0 1]

Data Headers
['N1' 'N2' 'N3' 'N4']


### Loading Data Method 2: Using StringEnumerator

Given the 4 requirements for the attribute and phenotype array, not all datasets necessarily satisfy those requirements. For example, a dataset may contain an attribute with values that are colors "red", "green", "blue". Since the eLCS scikit model can only work with numeric data, this dataset would not meet the requirements. Alternatively, a dataset may, for some reason, have missing phenotype data. Since the eLCS scikit model requires that the phenotype array is complete, this dataset would also not meet the requirements.

To make things more convenient, included in this package is an auxilliary data type called **String Enumerator** that makes it easy to transform datasets that do not meet the requirements into datasets that do.

For example, take the below dummy dataset:

In [3]:
import pandas as pd

#Read from CSV file
data = pd.read_csv("Datasets/Tests/StringData2.csv")

#Specify the dataset's phenotype label
classLabel = "phenotype"

#Derive the attribute and phenotype array using the phenotype label
dataFeatures = data.drop(classLabel,axis = 1).values
dataPhenotypes = data[classLabel].values

#Optional: Retrieve the headers for each attribute as a length n array
dataHeaders = data.drop(classLabel,axis=1).columns.values

print("Data Features")
print(dataFeatures)
print("\nData Phenotypes")
print(dataPhenotypes)
print("\nData Headers")
print(dataHeaders)

Data Features
[['male' 1.2 'young']
 ['female' 0.3 nan]
 ['female' -0.4 'old']
 [nan 0.0 'young']]

Data Phenotypes
['china' nan 'china' 'russia']

Data Headers
['N1' 'N2' 'N3']


This dummy dataset does not come close to meeting the dataset requirements for training. There exist many string types in the attribute and phenotype array, as well as missing phenotype data. Aside from not meeting the requirements, the data headers and phenotype label are not too descriptive. Below StringEnumerator cleans this up.

In [4]:
from DataCleanup import StringEnumerator

#Initialize StringEnumerator object with csv filepath and class label.
converter = StringEnumerator("Datasets/Tests/StringData2.csv","phenotype")

#Change Header Names to be more descriptive using changeHeaderName(currentName,newName)
converter.changeHeaderName("N1","Gender")
converter.changeHeaderName("N2","Numeric")
converter.changeHeaderName("N3","Age")

#Change Phenotype Label to be more descriptive using changeClassName(newName)
converter.changeClassName("Country")

'''
Convert attributes to numeric data using either:
-addAttributeConverterRandom(headerName):   Given an attribute name, randomly assigns each unique attribute value an
                                            integer value from 0 to n-1, where n = # of unique attribute values
-addAttributeConverter(headerName,array):   Given an attribute name, and an array of attribute values that will be
                                            converted, converter assigns each attribute value an integer value from
                                            0 to n-1 in the order of attribute values given in the array, where
                                            n = length of array
'''
converter.addAttributeConverterRandom("Gender")
converter.addAttributeConverter("Age",["old","young"])

'''
Convert phenotypes to numeric data using either
-addClassConverter(array)
-addClassConverterRandom()
Same functionality as the attribute converters
'''
converter.addClassConverterRandom()

#Convert all attributes using convertAllAttributes()
converter.convertAllAttributes()

#Get arrays using getParams()
headers,classLabel,dataFeatures,dataPhenotypes = converter.getParams()

print("Data Features")
print(dataFeatures)
print("\nData Phenotypes")
print(dataPhenotypes)
print("\nData Headers")
print(headers)
print("\nClass Label")
print(classLabel)

Data Features
[[ 0.   1.2  1. ]
 [ 1.  -0.4  0. ]
 [ nan  0.   1. ]]

Data Phenotypes
[0. 0. 1.]

Data Headers
['Gender' 'Numeric' 'Age']

Class Label
Country


As you can see, the StringEnumerator mapped all string attributes and phenotypes into numeric types, deleted the instance that was missing phenotype data, and made the data headers and class label more descriptive. Now, the data features and phenotypes are ready for training.

The StringEnumerator has 2 additional methods not shown above that can also be powerful in data transformation:
<ul>
    <li>deleteAttribute(headerName): deletes the specified attribute from all instances in the dataset</li>
    <li>deleteAllInstancesWithoutHeaderData(headerName): there may be situations where you only want to use data instances that does not have missing data for a specific attribute. This method deletes all instances who's specified attribute is missing</li>
</ul>

Even if the dataset satisfies all requirements, StringEnumerator can be used as an easy way to get data in the correct format without needing to use pandas, as shown below:
    

In [5]:
converter = StringEnumerator("Datasets/Tests/MissingFeatureData.csv","phenotype")
headers,classLabel,dataFeatures,dataPhenotypes = converter.getParams()

print("Data Features")
print(dataFeatures)
print("\nData Phenotypes")
print(dataPhenotypes)
print("\nData Headers")
print(headers)

Data Features
[[ 1. nan  1.  4.]
 [ 2.  0.  1. nan]
 [ 4. nan  1.  2.]
 [nan  1. nan  1.]
 [ 6. nan  1.  1.]]

Data Phenotypes
[1. 0. 1. 0. 1.]

Data Headers
['N1' 'N2' 'N3' 'N4']


All in all, StringEnumerator makes loading data in the correct format easy. It is relatively intuitive to use, and if anything invalid operation were done with it, built in checkers will raise contextually Exceptions to help you correct the error. We will be using it to load data for the rest of this user guide.

## Part 2: Initializing scikit-learn eLCS Classifier Object

### Basic Initialization

In [6]:
from eLCS import eLCS

model = eLCS()

Doing the above will initialize an eLCS classifier object using the default hyperparameters, that is now ready for training. However, in most cases, you would want to modify some hyperparameters to your needs. We list all of the tunable hyperparameters and their descriptions:

### Overview of all eLCS initialization parameters and default values

| Parameter Name | Requirements | Description | Default Value |
| :--- | :--- | :--- | :--- |
| learningIterations | non negative integer | The number of training cycles to run | 10000 |
| N | non negative integer | Maximum microclassifier population size (sum of classifier numerosities) | 1000 |
| p_spec | float from 0 - 1 | Probability of specifying an attribute during the covering procedure | 0.5 |
| nu (v) | float | Power parameter used to determine the importance of high accuracy when calculating fitness | 5 |
| chi (X) | float from 0 - 1 | The probability of applying crossover in the GA | 0.8 |
| upsilon (u) | float from 0 - 1 | The probability of mutating an allele within an offspring | 0.04 |
| theta_GA | non negative float | The GA threshold. The GA is applied in the correct set when the average time (# of iterations) since the last GA in the correct set is greater than theta_GA | 25 |
| theta_del | non negative integer | The deletion experience threshold; The calculation of the deletion probability changes once this threshold is passed | 20 |
| theta_sub | non negative integer | The subsumption experience threshold | 20 |
| acc_sub | float from 0 - 1 | Subsumption accuracy requirement | 0.99 |
| beta | float | Learning parameter; Used in calculating average correct set size | 0.2 |
| delta | float | Deletion parameter; Used in determining deletion vote calculation | 0.1 |
| init_fit | float | The initial fitness for a new classifier (typically very small, approaching but not equal to zero) | 0.01 |
| fitnessReduction | float | Initial fitness reduction in GA offspring rules | 0.1 |
| doSubsumption | boolean | Determines if subsumption is done in the learning process | True |
| selectionMethod | "tournament" or "roulette" | Determines GA selection method | "tournament" |
| theta_sel | float from 0 - 1 | The fraction of the correct set to be included in tournament selection | 0.5 |
| p_spec | float from 0 - 1 | Probability of specifying an attribute during the covering procedure | 0.5 |
| p_spec | float from 0 - 1 | Probability of specifying an attribute during the covering procedure | 0.5 |

There also exists a few hyperparameters related to the setup and evaluation of the training process:

| Parameter Name | Requirements | Description | Default Value |
| :--- | :--- | :--- | :--- |
| evalWhileFit | boolean | Determines if live tracking and evaluation is done during model training | False |
| trackingFrequency | non negative integer | Relevant only if evalWhileFit param is true. Conducts accuracy approximations and population measurements every "trackingFrequency" iterations. If param == 0, tracking done once every epoch | 0 |
| learningCheckpoints | numpy.ndarray of nonnegative integers | Relevant only if evalWhileFit param is true. Conducts detailed evaluation of model performance by finding precise training accuracy at the specified iteration count in the array. Iterations are 0 indexed. | empty numpy ndarray |
| discreteAttributeLimit | non negative integer OR "c" OR "d" | Multipurpose param. If it is a nonnegative integer, discreteAttributeLimit determines the threshold that determines if an attribute will be treated as a continuous or discrete attribute. For example, if discreteAttributeLimit == 10, if an attribute has more than 10 unique values in the dataset, the attribute will be continuous. If the attribute has 10 or less unique values, it will be discrete. Alternatively, discreteAttributeLimit can take the value of "c" or "d". See next param for this. | 10 |
| specifiedAttributes | numpy.ndarray of nonnegative integers of attribute indices | If discreteAttributeLimit == "c", attributes specified by index in this param will be continuous and the rest will be discrete. If "d", attributes specified by index in this param will be discrete and the rest will be continuous | empty numpy ndarray |
| discretePhenotypeLimit | non negative integer OR "c" OR "d" | Works similarly to discreteAttributeLimit. Multipurpose param. If it is a nonnegative integer, this param determines the continuous/discrete threshold for the phenotype. If it is "c" or "d", the phenotype is explicitly defined as continuous or discrete. For training to occur, the phenotype MUST be discrete | 10 |
| randomSeed | integer OR "none" | Set a constant random seed value to some integer (in order to obtain reproducible results). Put 'none' if none (pseudo-random algorithm runs) | "none" |

These hyperparameters can be set during initialization. There exists built in parameter checking to ensure each specified parameter is valid. Below is an example:


In [7]:
model = eLCS(learningIterations = 5000,evalWhileFit = True,trackingFrequency = 100)

## Part 3: Model Training and Testing

### model.fit(X, y) and how it works
Once the model is initialized with the hyperparameters you want, you can train the model by calling the fit(X,y) method, where X is the numpy.ndarray of attributes and y is the numpy.ndarray of phenotypes. Be sure both X and y satisfy the requirements specified in Part 1, or the parameter checker will raise an Exception. Below we demo the entire process of importing relevant packages, loading data, model initialization, and model training using the complete 6 bit multiplexer dataset:

In [8]:
from DataCleanup import StringEnumerator
from eLCS import eLCS
import numpy as np

converter = StringEnumerator("Datasets/Real/Multiplexer6.csv","class")
headers,classLabel,dataFeatures,dataPhenotypes = converter.getParams()

formatted = np.insert(dataFeatures,dataFeatures.shape[1],dataPhenotypes,1)
np.random.shuffle(formatted)
dataFeatures = np.delete(formatted,-1,axis=1)
dataPhenotypes = formatted[:,-1]

model = eLCS(learningIterations = 5000,evalWhileFit=True,learningCheckpoints=np.array([99,999,3999]),trackingFrequency=100)
trainedModel = model.fit(dataFeatures,dataPhenotypes)

trainedModel

eLCS(N=1000, acc_sub=0.99, beta=0.2, chi=0.8, delta=0.1,
   discreteAttributeLimit=10, discretePhenotypeLimit=10,
   doSubsumption=True, evalWhileFit=True, fitnessReduction=0.1,
   init_fit=0.01, learningCheckpoints=array([  99,  999, 3999, 4999]),
   learningIterations=5000, nu=5, p_spec=0.5, randomSeed='none',
   selectionMethod='tournament',
   specifiedAttributes=array([], dtype=float64), theta_GA=25, theta_del=20,
   theta_sel=0.5, theta_sub=20, trackingFrequency=100, upsilon=0.04)

The fit function returns a trained model. Below we describe the entire training process:

<ul>
    <li> Step 1: Model verifies X and y are numeric, and that y has no missing values. If not, an Exception is raised. </li>
    <li> Step 2: Model performs analysis on X and y. Using the discreteAttributeLimit and specifiedAttributes parameters, it determines and enumerates which attributes are discrete and which attributes are continuous. Using the discretePhenotypeLimit param, it determines whether the phenotype is discrete or continuous. If the phenotype is found to be continuous, the model will raise an Exception. </li>
    <li> Step 3: Model completes the specified number of training iterations. If evalWhileFit is True, during the training process, performance data will be collected and stored for later analysis (specified in depth in Part 4). Below is a simplified diagram of the training cycle</li>
</ul>

<img src="LearningCycle.png">

### model.predict(X), model.predict_proba(X)

Once the model has finished training, you can call the predict(X) method to return an numpy.ndarray of class predictions given an array of unlabelled instances. The predict method works by using the final rule population of the model to vote on the most probable class based on classifier fitness and numerosity. Before making a prediction, parameter checkers again ensure X is a valid input (fully numeric numpy.ndarray). We refer back to the trained model above.

In [9]:
trainedModel.predict(dataFeatures)

array([0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0.,
       1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0.,
       1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0.])

You can also call the predict_proba(X) method to return an nxm numpy.ndarray of phenotype probabilities, where n = number of data instances and m = number of distinct discrete phenotypes.

In [10]:
trainedModel.predict_proba(dataFeatures)

array([[0.94326616, 0.05673384],
       [0.08833685, 0.91166315],
       [0.00749316, 0.99250684],
       [0.00362867, 0.99637133],
       [0.08754882, 0.91245118],
       [0.07842866, 0.92157134],
       [0.00269726, 0.99730274],
       [0.92032932, 0.07967068],
       [0.00523186, 0.99476814],
       [0.96561194, 0.03438806],
       [0.8894203 , 0.1105797 ],
       [0.88335153, 0.11664847],
       [0.07041506, 0.92958494],
       [0.92874507, 0.07125493],
       [0.801558  , 0.198442  ],
       [0.06730557, 0.93269443],
       [0.99731263, 0.00268737],
       [0.09404663, 0.90595337],
       [0.9447572 , 0.0552428 ],
       [0.12666549, 0.87333451],
       [0.01029632, 0.98970368],
       [0.75533508, 0.24466492],
       [0.060733  , 0.939267  ],
       [0.90011669, 0.09988331],
       [0.0116983 , 0.9883017 ],
       [0.72652156, 0.27347844],
       [0.99724716, 0.00275284],
       [0.06841659, 0.93158341],
       [0.99313414, 0.00686586],
       [0.03288388, 0.96711612],
       [0.

### Cross Validation and Scoring
You can score a set of predictions using the score(X,y) method, where X is the unlabelled test data and y is associated list of correct class labels. By default, score(X,y) uses balanced accuracy to score.


In [11]:
trainedModel.score(dataFeatures,dataPhenotypes)

1.0

You can also use different scoring metrics to score the model. We will do this with a quick cross validation on the model. Below we will run a 3 fold CV on the trained multipler model from above. Again, by default, balanced accuracy is used to score each partition.

In [12]:
from sklearn.model_selection import cross_val_score
import numpy as np

np.mean(cross_val_score(trainedModel,dataFeatures,dataPhenotypes,cv=3))

0.8424242424242424

If you prefer to use a scoring method other than balanced accuracy during CV (e.g. accuracy_score, precision_score, recall_score, f1_score), that can be specified as well via the standard scoring parameter.

In [13]:
np.mean(cross_val_score(trainedModel,dataFeatures,dataPhenotypes,cv=3,scoring="recall"))

0.7787878787878787

Below we demonstrate a scoring method that calls predict_prob(X):

In [14]:
np.mean(cross_val_score(trainedModel,dataFeatures,dataPhenotypes,cv=3,scoring="roc_auc"))

0.9476584022038567

### ROC/AUC/PRC curves

TBA

## Part 4: Data Collection and Export

### evalWhileFit, trackingFrequency, learningCheckpoints
As mentioned in Part 2, there exists parameters **evalWhileFit**, **trackingFrequency**, and **learningCheckpoints** that determines evaluation during the training process.

**evalWhileFit** is a boolean that determines whether evaluation is done during training or not. The benefit to doing evaluation during training is that you will be able to collect data on how the rule population and general statistics of the model changes over many iterations. The downside to doing evaluation during training is that evaluation always slows down the training process, the amount dependent on how much evaluation is being done.

If evalWhileFit is True, then the trackingFrequency and learningCheckpoint parameters become relevant. These two parameters determine two kinds of data tracking.

**trackingFrequency**: Even if evalWhileFit is true, at the end of every iteration, this following information is saved:
<ul>
    <li>Macropopulation size</li>
    <li>Micropopulation size</li>
    <li>Match set size</li>
    <li>Correct set size</li>
    <li>Average iteration age (experience) of classifiers in correct set</li>
    <li>Number of classifiers subsumed in iteration</li>
    <li>Number of crossover operations performed in iteration (GA operation)</li>
    <li>Number of mutation operations performed in iteration (GA operation)</li>
    <li>Number of covering operations performed in iteration</li>
    <li>Number of macroclassifiers deleted in iteration</li>
    <li>Total training time</li>
    <li>Total matching time</li>
    <li>Total deletion time</li>
    <li>Total subsumption time</li>
    <li>Total selection time</li>
    <li>Total evaluation time</li>
</ul>

trackingFrequency thus determines the frequency at which 2 additional pieces of information are collected in addition to the already collected data above:
<ul>
    <li>Approximate Accuracy</li>
    <li>Average Population Generality</li>
</ul>
This distinction is made because approximate accuracy and average population generality are statistics that are time intensive to compute, and thus not included by default in every iteration.

If trackingFrequency == 100 for example, then these two statistics would be collected once every 100 iterations. If trackingFrequency == 0 (the default value), then these two statistics would be collected once every epoch. At the final iteration, full tracking data is collected regardless of trackingFrequency.

**learningCheckpoints**: learningCheckpoints is a numpy.ndarray that specifies at what iterations a complete training evaluation of the rule population should be completed. Note: iterations are always zero indexed (so the first iteration is enumerated as iteration 0). By default, if evalWhileFit is True, the only learningCheckpoint is the final iteration, where a complete training evaluation is completed on the final rule population. However, evaluations can be done as frequently as specified. An evaluation of the final rule population is done regardless of if was included in learningCheckpoints or not.

At each evaluation, the following data is saved:
<ul>
    <li> Training Accuracy </li>
    <li> Instance Coverage </li>
    <li> The complete rule population at the end of that iteration </li>
</ul>

All of the aforementioned data is saved within an IterationRecord object, under the **record** attribute of the scikit eLCS.

### Exporting and Accessing Iteration Tracking Data
As mentioned above, the iteration tracking data collected (based on trackingFrequency) is stored in the **record** attribute of the eLCS. The package includes a few getter methods that allow you to access parts of this data. It is important to note that these methods are in no way exhaustive to all of the data the tracker collects, but only provides a few arbitrarily "key" statistics!

| Method Name | Description |
| :--- | :--- |
| model.getMacroPopulationSize(iterationNumber) | Retrieves the macropopulation size of the rule population at the specified iteration number |
| model.getFinalMacroPopulationSize() | Retrieves the macropopulation size of the final rule population |
| model.getMicroPopulationSize(iterationNumber) | Retrieves the micropopulation size of the rule population at the specified iteration number |
| model.getFinalMicroPopulationSize() | Retrieves the micropopulation size of the final rule population |
| model.getPopAvgGenerality(iterationNumber) | Retrieves the average generality (% of condition that is not specified) of the rule population at the specified iteration number |
| model.getFinalPopAvgGenerality() | Retrieves the average generality (% of condition that is not specified) of the final rule population |
| model.getTimeToTrain(iterationNumber) | Retrieves the total training time (in seconds) of the rule population at the specified iteration number |
| model.getFinalTimeToTrain() | Retrieves the total training time (in seconds) of the final rule population |

Remember that iterationNumber is 0 indexed (the first iteration is iteration 0). Also keep in mind that the average generality attribute is not available at every iteration, and is only available on iterations where trackingFrequency specified it to run (the approximate accuracy attribute is similarly not always available, but it is not accessible via any getter).

In [15]:
#Macropopulation Size at iteration 258
print(trainedModel.getMacroPopulationSize(258))

#Final Macropopulation Size
print(trainedModel.getFinalMacroPopulationSize())

#Micropopulation Size at iteration 1390
print(trainedModel.getMicroPopulationSize(1390))

#Final Micropopulation Size
print(trainedModel.getFinalMicroPopulationSize())

#Average Population Generality at iteration 299
print(trainedModel.getPopAvgGenerality(299))

#Final Average Population Generality
print(trainedModel.getFinalPopAvgGenerality())

#Total time to train at the end of iteration 2500
print(trainedModel.getTimeToTrain(2500))

#Total time to train the model
print(trainedModel.getFinalTimeToTrain())

59
233
373
1000
0.48995983935742987
0.5401666666666665
2.278717041015625
5.8592689037323


The reason we decided to only make a fraction of the tracking data accessible via getter methods is because the package includes a powerful **exporting method** called **exportIterationTrackingDataToCSV()** that exports the entire tracking data record into a CSV file named **iterationData.csv**.

In [16]:
trainedModel.exportIterationTrackingDataToCSV()

The exported CSV is below:

In [17]:
iterationData = pd.read_csv("iterationData.csv")
display(iterationData)

Iteration  Accuracy (approx)  Average Population Generality  \
0             0                NaN                            NaN   
1             1                NaN                            NaN   
2             2                NaN                            NaN   
3             3                NaN                            NaN   
4             4                NaN                            NaN   
5             5                NaN                            NaN   
6             6                NaN                            NaN   
7             7                NaN                            NaN   
8             8                NaN                            NaN   
9             9                NaN                            NaN   
10           10                NaN                            NaN   
11           11                NaN                            NaN   
12           12                NaN                            NaN   
13           13                NaN                            NaN   
14           14                NaN                            NaN   
15           15                NaN                            NaN   
16           16                NaN                            NaN   
17           17                NaN                            NaN   
18           18                NaN                            NaN   
19           19                NaN                            NaN   
20           20                NaN                            NaN   
21           21                NaN                            NaN   
22           22                NaN                            NaN   
23           23                NaN                            NaN   
24           24                NaN                            NaN   
25           25                NaN                            NaN   
26           26                NaN                            NaN   
27           27                NaN                            NaN   
28           28                NaN                            NaN   
29           29                NaN                            NaN   
...         ...                ...                            ...   
4970       4970                NaN                            NaN   
4971       4971                NaN                            NaN   
4972       4972                NaN                            NaN   
4973       4973                NaN                            NaN   
4974       4974                NaN                            NaN   
4975       4975                NaN                            NaN   
4976       4976                NaN                            NaN   
4977       4977                NaN                            NaN   
4978       4978                NaN                            NaN   
4979       4979                NaN                            NaN   
4980       4980                NaN                            NaN   
4981       4981                NaN                            NaN   
4982       4982                NaN                            NaN   
4983       4983                NaN                            NaN   
4984       4984                NaN                            NaN   
4985       4985                NaN                            NaN   
4986       4986                NaN                            NaN   
4987       4987                NaN                            NaN   
4988       4988                NaN                            NaN   
4989       4989                NaN                            NaN   
4990       4990                NaN                            NaN   
4991       4991                NaN                            NaN   
4992       4992                NaN                            NaN   
4993       4993                NaN                            NaN   
4994       4994                NaN                            NaN   
4995       4995                NaN                            NaN   
4996

If you rerun the model with different hyperparameters and export again, make sure you **delete the old iterationData.csv file**, or the new data will overwrite the old data into a single merged file.

Of course, once the data is exported to a CSV, you can use Excel to plot trendlines for each statistic. As a demonstration of the potential of this CSV however, we will use pandas to read the csv file data, and plot out some of these trendlines using matplotlib below:

In [18]:
print("TBA")

TBA


### Exporting and Accessing Rule Population Data

As mentioned above, the rule population data collected (based on learningCheckpoints) is stored in the record attribute of the eLCS. The package includes a few getter methods that allow you to access parts of this data. It is important to note that these methods are in no way exhaustive to all of the data the tracker collects, but only provides a few arbitrarily "key" statistics!

| Method Name | Description |
| :--- | :--- |
| model.getAccuracy(iterationNumber) | Retrieves the evaluation accuracy of the rule population at the specified iteration number |
| model.getFinalAccuracy() | Retrieves the evaluation accuracy of the final rule population |

Remember that iterationNumber is 0 indexed (the first iteration is iteration 0). Also keep in mind that the evaluation accuracy is not available at every iteration, and is only available on iterations where learningCheckpoint specified it to run.

In [19]:
#Evaluation Accuracy at iteration 99
print(trainedModel.getAccuracy(99))

#Evaluation Accuracy at iteration 999
print(trainedModel.getAccuracy(999))

#Evaluation Accuracy or Final Rule Population
print(trainedModel.getFinalAccuracy())

0.734375
0.953125
1.0


Similar to tracking data, the package includes two powerful **exporting methods** that will allow you to export available rule populations to a CSV file named **populationData.csv**.

| Method Name | Description |
| :--- | :--- |
| model.exportRulePopulationAtIterationToCSV(iterationNumber,headerNames,classLabel) | Exports evaluation accuracy, instance coverage, and the entire rule population at the specified iteration number |
| model.exportFinalRulePopulationToCSV(headerNames,classLabel) | Exports evaluation accuracy, instance coverage, and the entire rule population of the final rule population |

The headerNames and classLabel params are optional. If they are not provided, default header and class names will be populated. But they make the exported csv more descriptive.

A nice feature about all of the rule population methods is that even if **evalWhileFit** == False during training, you can still call **getAccuracy(finalIterationNumber)**, **getFinalAccuracy()**, and **exportFinalRulePopulationToCSV(headerNames, classLabel)** successfully without raising an Exception. Even if the evaluation wasn't done during training, these methods will run the evaluation on the final rule population if necessary during the call, and return/export your desired data anyway.

In [20]:
trainedModel.exportRulePopulationAtIterationToCSV(99,headers,classLabel)

The exported CSV is below:

In [21]:
populationData = pd.read_csv("populationData.csv",skiprows=3)
display(populationData)

A_0  A_1  R_0  R_1  R_2  R_3  class   Fitness  Accuracy  Numerosity  \
0   1.0    #  0.0    #  1.0  0.0    1.0  0.077760  0.600000           2   
1     #  1.0    #    #    #    #    0.0  0.023078  0.470588           2   
2     #    #    #  1.0    #  0.0    1.0  0.052922  0.555556           1   
3   1.0    #  1.0    #  1.0    #    1.0  0.203463  0.727273           1   
4     #  0.0  0.0  0.0    #    #    0.0  0.366648  0.818182           1   
5   0.0  1.0  0.0  1.0    #    #    1.0  1.000000  1.000000           1   
6   1.0  1.0  1.0    #  0.0  1.0    1.0  1.000000  1.000000           2   
7     #    #  0.0    #  1.0    #    0.0  0.039434  0.523810           1   
8   0.0  0.0    #    #  0.0  1.0    1.0  0.014458  0.428571           1   
9   0.0    #  0.0  1.0    #  0.0    0.0  0.014458  0.428571           1   
10  0.0    #    #  1.0  0.0    #    1.0  0.237305  0.750000           1   
11    #  0.0  1.0    #    #  1.0    1.0  0.168070  0.700000           1   
12  0.0    #  0.0  1.0    #    #    0.0  0.019404  0.454545           1   
13    #  1.0    #  0.0  0.0  1.0    1.0  0.060927  0.571429           1   
14  1.0  0.0  1.0    #    #    #    0.0  0.052922  0.555556           1   
15    #  1.0    #    #    #    #    1.0  0.035467  0.512821           1   
16    #  0.0  0.0  1.0    #  0.0    0.0  0.327680  0.800000           1   
17    #    #  0.0    #  0.0  1.0    0.0  0.095367  0.625000           1   
18  1.0    #  0.0    #  1.0    #    1.0  0.185934  0.714286           1   
19    #  0.0  1.0    #    #  0.0    1.0  1.000000  1.000000           1   
20    #  0.0    #    #  0.0    #    1.0  0.001509  0.272727           1   
21  0.0  0.0  1.0  1.0    #  1.0    1.0  0.020272  0.700000           1   
22  1.0  1.0    #    #  0.0  1.0    1.0  1.000000  1.000000           1   
23    #    #  0.0  1.0    #  0.0    0.0  0.031250  0.500000           1   
24    #  0.0  0.0  1.0  1.0    #    0.0  1.000000  1.000000           1   

    Iteration Initialized  Specificity  
0                       0     0.666667  
1                       1     0.166667  
2                       2     0.333333  
3                       5     0.500000  
4                       6     0.500000  
5                       8     0.666667  
6                      11     0.833333  
7                      13     0.333333  
8                      14     0.666667  
9                      15     0.666667  
10                     20     0.500000  
11                     21     0.500000  
12                     23     0.500000  
13                     24     0.666667  
14                     26     0.500000  
15                     27     0.166667  
16                     29     0.666667  
17                     37     0.500000  
18                     40     0.500000  
19                     51     0.500000  
20                     55     0.333333  
21                     55     0.833333  
22                     75     0.666667  
23                     77     0.500000  
24                     77     0.666667

If you rerun the model with different hyperparameters and export again, make sure you **delete the old populationData.csv file**, or the new data will overwrite the old data into a single merged file.

In [22]:
trainedModel.exportFinalRulePopulationToCSV(headers,classLabel)

populationData2 = pd.read_csv("populationData.csv",skiprows=3)
display(populationData2)

A_0  A_1  R_0  R_1  R_2  R_3  class   Fitness  Accuracy  Numerosity  \
0    1.0    #  0.0    #  1.0  0.0    1.0  0.031752  0.501597           1   
1      #  1.0    #    #    #    #    0.0  0.031438  0.500600           4   
2      #    #    #  1.0    #  0.0    1.0  0.031375  0.500400           2   
3    1.0    #  1.0    #  1.0    #    1.0  0.238571  0.750799           1   
4      #  0.0  0.0  0.0    #    #    0.0  0.237938  0.750400           6   
5      #    #  0.0    #  1.0    #    0.0  0.031376  0.500401           1   
6    0.0    #  0.0  1.0    #  0.0    0.0  0.030751  0.498392           1   
7    0.0    #    #  1.0  0.0    #    1.0  0.237942  0.750403           1   
8      #  0.0  1.0    #    #  1.0    1.0  0.236671  0.749599           1   
9    0.0    #  0.0  1.0    #    #    0.0  0.030998  0.499192           1   
10     #  1.0    #  0.0  0.0  1.0    1.0  0.031250  0.500000           2   
11   1.0  0.0  1.0    #    #    #    0.0  0.031250  0.500000           2   
12     #  1.0    #    #    #    #    1.0  0.030937  0.498995           3   
13     #  0.0  0.0  1.0    #  0.0    0.0  0.234764  0.748387           2   
14     #    #  0.0    #  0.0  1.0    0.0  0.095522  0.625202           5   
15   1.0    #  0.0    #  1.0    #    1.0  0.236036  0.749196           6   
16     #  0.0  1.0    #    #  0.0    1.0  0.239867  0.751613           9   
17     #    #  0.0  1.0    #  0.0    0.0  0.094903  0.624390           1   
18     #  0.0  0.0  1.0  1.0    #    0.0  0.030744  0.498371           1   
19     #  0.0  1.0  1.0    #  1.0    1.0  0.239901  0.751634           2   
20     #    #  0.0    #  1.0    #    1.0  0.031123  0.499592           2   
21     #  0.0  0.0    #    #    #    0.0  0.237305  0.750000          15   
22   0.0    #  1.0    #    #  1.0    1.0  0.237305  0.750000           3   
23   0.0  1.0    #    #    #    #    1.0  0.031122  0.499588           1   
24     #  0.0  0.0    #    #  1.0    0.0  0.236654  0.749588           5   
25     #    #  0.0  0.0  0.0  1.0    0.0  0.236002  0.749175           2   
26     #  0.0    #    #    #  1.0    1.0  0.031250  0.500000           1   
27   1.0  1.0    #    #  0.0    #    0.0  0.031509  0.500826           2   
28     #    #    #  1.0    #  1.0    1.0  0.237634  0.750208           8   
29     #    #  0.0  1.0    #    #    0.0  0.031120  0.499584           1   
..   ...  ...  ...  ...  ...  ...    ...       ...       ...         ...   
203    #    #    #  0.0  0.0    #    0.0  0.241782  0.752809           1   
204    #    #    #  1.0  0.0    #    0.0  0.032531  0.504032           1   
205    #  1.0    #  0.0  0.0    #    0.0  0.244084  0.754237           2   
206  1.0    #    #  0.0    #  0.0    0.0  0.230447  0.745614           1   
207    #    #    #  1.0  1.0    #    1.0  0.237305  0.750000           1   
208  1.0    #    #    #  0.0  1.0    1.0  0.028304  0.490196           1   
209    #  0.0  1.0  1.0  0.0  1.0    0.0  0.025480  0.480000           1   
210  0.0    #    #    #  1.0  1.0    0.0  0.031250  0.500000           1   
211    #  0.0    #  0.0  0.0    #    0.0  0.241410  0.752577           1   
212  0.0  1.0    #  1.0    #  1.0    0.0  0.000000  0.000000           1   
213  0.0  0.0  1.0    #    #  0.0    0.0  0.000000  0.000000           1   
214    #  1.0    #  1.0    #  1.0    0.0  0.000000  0.000000           1   
215  1.0    #    #  1.0    #    #    0.0  0.031250  0.500000           2   
216    #  1.0    #    #  0.0    #    0.0  0.032143  0.502825           1   
217  0.0  0.0  1.0  1.0    #    #    0.0  0.000000  0.000000           1   
218  1.0    #  1.0    #  0.0  1.0    0.0  0.031250  0.500000           1   
219  1.0    #    #  0.0  1.0    #    1.0  0.247621  0.756410           1   
220  0.0  0.0  0.0  0.0    #    #    1.0  0.000000  0.000000           1   
221  1.0    #  0.0  0.0  0.0    #    0.0  0.249534  0.757576           1   
222  0.0  1.0    #    #  0.0    #    0.0  0.031250  0.500000           1   
223  0.0  0.0    #    #  0.0    #    1.0  0.028847  0

## Conclusion

By now, you should be able to use eLCS deftly, from initialization, to training, to evaluation. Have fun!